// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Stock.Data;

#nullable disable

namespace Stock.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240730045745_adddatatocategory")]
    partial class adddatatocategory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Stock.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("AddValue")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<double>("Quantity")
                        .HasColumnType("float");

                    b.Property<double>("SubValue")
                        .HasColumnType("float");

                    b.Property<double>("TotalQ")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddValue = 0.0,
                            Name = "Action",
                            Quantity = 0.0,
                            SubValue = 0.0,
                            TotalQ = 0.0
                        },
                        new
                        {
                            Id = 2,
                            AddValue = 0.0,
                            Name = "Shop",
                            Quantity = 0.0,
                            SubValue = 0.0,
                            TotalQ = 0.0
                        },
                        new
                        {
                            Id = 3,
                            AddValue = 0.0,
                            Name = "Bis",
                            Quantity = 0.0,
                            SubValue = 0.0,
                            TotalQ = 0.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
